### ISSUE TITLE
Users not on radar after nearby notification

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#101]
From User
"After notification that a friend is nearby, open the app and those people are NOT on the radar. "

**Comment by alexsup** [comment]
@jcampbell05 As far as I am aware, this is a simple process.

I am much more confident in the new API and would like to switch as soon as possible

**Comment by jcampbell05** [comment]
@alexsup Cool I'll be doing some work on the Radar this sprint so I can look into background updates :)

**Comment by alexsup** [comment]
@jcampbell05 Can you update this issue with your information

**Comment by jcampbell05** [comment]
So from the perspective of the user the Radar doesn't match up with their expectation of what they believe they should see, this means the following:

- They get a notification of who's nearby, they open the app and they can't find them.
- They open the app and it appears as if it thinks they are in another location.

I believe we can fix it the following way (Some are already implemented):

- Better Feedback: Right now we may know where they are accurately but we haven't yet fetched the new list of nearby users. This means the Radar is actually showing an old Result until the app is able to fetch who is nearby. 

The problem is made worse the longer it takes to pull down the new users.

We merged (https://github.com/Supmenow/Sup-iOS/pull/1214)  in a tweak where we show the loading state when we are currently updating to let them know the Radar is showing an old result and we are getting the new results.

We need to tweak the design of the loading state as the current design isn't that nice since it blocks the user from interacting with the Radar. I have a Spike for a new loading design I'll show Rhys (https://github.com/Supmenow/Sup-iOS/pull/1213)

- Better Radar Item Layout: Right now the radar allows users to overlap which can obscure the person who is now nearby - we've experimented with different layouts in the past so based on what we learn't I tweaked the layout slightly.

I added the current user to the middle of the radar to help guide their eyes to where they should be looking. Hopefully they will notice the new person nearby.

We reduced the size of the users back to their original values to increase the amount of space and decreasing the likely hood they will overlap.

As well I added additional padding to the centre of the radar, in-effect turning the area where other users can be positioned into a doughnut. This means if a user is 0 minutes away they can no-longer be immediately in the centre but around the edge of the current user. This means the radius of the circle the users are positioned on is greater and decreases the chance they will overlap.

This was merged in these PRs:

- https://github.com/Supmenow/Sup-iOS/pull/1211
- https://github.com/Supmenow/Sup-iOS/pull/1186
- https://github.com/Supmenow/Sup-iOS/pull/1184

- No Background Fetching: Currently the App has to update as soon as the user opens the App. In the future we could:

- User Opportunistic Updates
- Trigger Background Update on location update 
- Background Update before allowing iOS to show the notification.
- Deliver the nearby users inside of the actual Notification payload.

If we implement this when the user opens the app we should have already got who is nearby and be able to display them immediately.

- No Hints For Out Of Date Notifications: Currently if a notification is out of date, there is no hint to the user. They are simply chucked into the radar and left to figure out where the new user is and even if it's relevant anymore.

In the future we could have a special screen we could present to them with additional information like "This was in Covent Garden 5 minutes ago".

**Comment by alexsup** [comment]
@jcampbell05 I think the solution to this is the API.

Both from who's nearby and the activity API.

We should start with the activity API as it's the least intrusive.

**Comment by jcampbell05** [comment]
@alexsup  API will defiantly be the longer-term solution but will need for me to tweak the infrastructure a little.

What do you mean less intrusive?

I don't think it matters which we do first, implementing the actual API calls etc is the easy bit :)

**Comment by alexsup** [comment]
@jcampbell05 Less intrusive as less changes your end (assumed) and provides a useful "last seen" information.

I'd love to trigger a badge for nearby notifications too.

**Comment by jcampbell05** [comment]
@alexsup I think the main bulk of the work will be setting up a proper API infrastructure. Switching the firebase calls to API ones after that should be easy.

Then after we've done that there will be more infrastructure work to add in background fetches to actually solve the original problem. (Until then these API calls would potentially just be tweaks with minor performance gains due to us normalizing)

What do you mean by badge?

**Comment by jcampbell05** [comment]
Also API removes need for app to pull down everyone and then filter so will be much faster :)

**Comment by jcampbell05** [comment]
https://www.buglife.com/apps/sup/reports/221 - Another report of this issue.

**Comment by jcampbell05** [comment]
Seems to be fixed in latest `dev`
