### ISSUE TITLE
Hangout screen shows all users when none are nearby

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#102]
From User
"When no friends are on the radar, and you click “Hangout” to invite someone - it shows ALL friends, not just those on SUP. No way to filter this list to just SUP users - which makes it difficult when you have 6k contacts in your phone"

**Comment by jcampbell05** [comment]
Will discuss with Rhys when he arrives Wednesday

**Comment by alexsup** [comment]
@jcampbell05 edge case.

Friend UI needs fixed

@Dannylowney Please add this to your list for Rhys.

Closing. Move to Jira after Rhys

**Comment by jcampbell05** [comment]
@alexsup  I think we could just simplify it all by making it list all friends in distance order (people not on sup at the bottom).

We should allow users to search list. 

On the radar we should allow users to tap on a users profile and start a hangout with them directly.

In addition I think we could combine the invite screen, friends and blocked users list into one Friends Screen and replace the settings screen so user can see their friends, people they can invite and who they've blocked in one tap :)
