### ISSUE TITLE
Combine Friends, Invite and Blocked List

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#104]
So our UI ends up like this and we have one unified UI:

```
---------------------
Friends On Sup
---------------------
Contacts Who Can Be Invited
---------------------
Blocked User
---------------------
```

**Comment by Dannylowney** [comment]
I like it 👍

**Comment by alexsup** [comment]
@jcampbell05 @Dannylowney not an issue.

A feature. Closed.

Please move to to Trello / Jira backlog if you would like actioned.

We can build into future sprints post designer.

**Comment by jcampbell05** [comment]
@alexsup  I think we should do this but I'll talk to Rhys :)
