### ISSUE TITLE
Can we auto-fill the share to Facebook Messenger Text

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#109]
Danny would like for us to see if this is possible.

**Comment by roger-tan** [comment]
https://developers.facebook.com/docs/sharing/ios/send-button could be a solution?

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan not an issue.

This is a feature. Closed.

Please don't get dragged into to scope creap by disguising them as issues.
