### ISSUE TITLE
List of users to invite resets every time we open the app.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#114]
Rich would like for us to keep track of where we last were in the list, potentially the server could handle this.

But I think this issue is moot if we fix #113 and #112

**Comment by jcampbell05** [comment]
@alexsup I think since the list is randomised now this no longer makes sense, since we can just show a different user each time the app is re-opened.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan Let's leave this as randomised.

Is it truly randomised?

**Comment by roger-tan** [comment]
Yes, it's randomized!

**Comment by jcampbell05** [comment]
@alexsup As random as our 21st century computer chips allow us to be.
