### ISSUE TITLE
Users do not wish to login via Facebook

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#115]
Users would like an alternative method to login.

We have started implementing a login process with Digits instead.

**Comment by roger-tan** [comment]
We already started to implement to get a different provider to use Sup. [https://github.com/Supmenow/Sup-iOS/pull/1215](Digitsl)

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan This is closed due to not being a priority.

It is part of a future sprint and requires careful planning and thought as it requires a backend implementation (AKA you guys using the API), design and Android.
