### ISSUE TITLE
Mixpanel "Sup Friends" property being saved as a string not an integer

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#116]
You can see this by mixpanel -> segmentation -> sup friends -> it will have A next to the name rather than 1
@roger-tan Please cast to integer :)

Thanks

**Comment by roger-tan** [comment]
No need to cast to integer. Just need to change the type on MixPanel by doing like this

<img width="483" alt="screenshot 2016-07-04 12 26 03" src="https://cloud.githubusercontent.com/assets/3829527/16559118/898b52be-41e2-11e6-93fb-1e02798b6049.png">

**Comment by alexsup** [comment]
@roger-tan Reopened.

**Comment by alexsup** [comment]
@roger-tan For danny, this needs to be a number I'm afraid...

https://mixpanel.com/docs/properties-or-segments/property-data-types

I'm sure there's a way 👍

**Comment by roger-tan** [comment]
It's already casted as Integer or NSNumber. There is no solution except the casting option providing from MixPanel UI.

<img width="277" alt="screenshot 2016-07-04 14 34 05" src="https://cloud.githubusercontent.com/assets/3829527/16562291/7b65e444-41f4-11e6-9cb3-eab76e5f1598.png">

**Comment by roger-tan** [comment]
Because it's always incremented, so MixPanel know that it's a Integer. Sup
Friends cannot be incremented.

On Tue, Jul 5, 2016 at 3:01 PM Alex Barton <notifications@github.com> wrote:

> @roger-tan <https://github.com/roger-tan> what is the difference between
> this and "Flares Created"?
>
> "Flares Created" is an int in mix panel :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Supmenow/sup-ios-issues/issues/116#issuecomment-230486363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADpvF03VJrB9gmG2G5v9YrYCVbbtOVqkks5qSmN9gaJpZM4JEP64>
> .
>
-- 
*___________________________________*
Roger TAN⎥Mobile Software Engineer
roger@supmenow.com⎥supmenow.com <https://supmenow.com/home-page-b/>
Sup

Runway East
10 Finsbury Square London
EC2A 1AF

**Comment by alexsup** [comment]
@roger-tan please contact mix panel to ask how to fix this :)

**Comment by jcampbell05** [comment]
Whats the latest on this ?

**Comment by roger-tan** [comment]
Moved to "Sup Friends" to "Friends"
