### ISSUE TITLE
Prompt a message if we try to invite a user for the first time

### ISSUE THREAD

**Issue by roger-tan** [Supmenow/sup-ios-issues#117]
If I click for the button to invite someone for the first time, we should alert the user about the behavior!

**Comment by jcampbell05** [comment]
@Dannylowney ?

**Comment by Dannylowney** [comment]
@roger-tan what do you mean? why should we? how might it look?

**Comment by roger-tan** [comment]
When you are in radar and you see a list of contacts. We should get an alert when they press + Button to add a friends on Sup that we are going to send a text message on behalf of the user.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan @Dannylowney This is not an issue.

Closing.

**Comment by alexsup** [comment]
@roger-tan Please move to trello :)
