### ISSUE TITLE
Can we improve this loading UI?

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#118]
This is really odd.

Surely there shouldn't be irrelevant data on the screen when loading?

![unnamed 19](https://cloud.githubusercontent.com/assets/13382954/16726261/3a1c9fd2-4753-11e6-8a45-88f9e2704730.png)

**Comment by jcampbell05** [comment]
So your issue is ?

**Comment by alexsup** [comment]
It's shit

**Comment by alexsup** [comment]
It's shit

*___________________________________*

*Alex⎥CTO*

*alex@supmenow.com <alex@supmenow.com>⎥supmenow.com <http://supmenow.com/>*

*Sup*

*Runway East *

*10 Finsbury Square*

*London*

* EC2A 1AF *

**Comment by jcampbell05** [comment]
What exactly do you want to change improve ?  Good examples include "I can't see the user's name" or "this is squashed on a small screen" or "this is being shown before the contacts have loaded".

I don't know how you want me to improve it or what the irrelevant data you speak of is or why it's bad :)

I also need some context as to if you disallowed things such as access to contacts :).

**Comment by alexsup** [comment]
When a loading screen is present, why would it have irrelevant information?

1. What is 25 mins away? Nothing. Why is it here? Because we didn't design for it. Shouldn't be here while screen is loading. Perhaps fade in post nearby load. Or is replaced with no one nearby and doesn't show.

2. Add friends to the radar? This makes no sense. Unless the user has no contacts? Under what circumstances is this triggered?

**Comment by jcampbell05** [comment]
@alexsup okay could we move those into two individual issues and carry the conversation on there.

For now I am closing this.
