### ISSUE TITLE
Some Supstas are receiving duplicate notifications.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#12]
It seems that some users are currently receiving duplicate notifications.

![img_4991](https://cloud.githubusercontent.com/assets/1484989/15141663/09495214-1699-11e6-8254-ba7cda5d9e28.PNG)

Will mark as "waiting input" until we can confirm what the issue is.

**Comment by alexsup** [comment]
@jcampbell05 I believe this is to do with multiple records per user in our notification services.

**Comment by jcampbell05** [comment]
@alexsup makes sense since it is effecting one of our beta users. We should look into this when we start our migration away from Parse.

**Comment by alexsup** [comment]
@jcampbell05 Closing this for now.

**Comment by jcampbell05** [comment]
Just got this

**Comment by alexsup** [comment]
@jcampbell05 Only one message is being sent to the notification server

**Comment by jcampbell05** [comment]
@alexsup okay let's keep this open until we figure out what is happening.

**Comment by alexsup** [comment]
@jcampbell05 Still nothing.

**Comment by alexsup** [comment]
@jcampbell05 I'm closing this.
