### ISSUE TITLE
When loading we should hide distance label

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#120]
Feedback from @alexsup:

What is 25 mins away? Nothing. Why is it here? Because we didn't design for it. Shouldn't be here while screen is loading. Perhaps fade in post nearby load. Or is replaced with no one nearby and doesn't show.

![image](https://cloud.githubusercontent.com/assets/1484989/16762144/266c3c04-481b-11e6-83f7-c97d00d1b86f.png)

**Comment by alexsup** [comment]
@jcampbell05 Initially reported through buglife

**Comment by jcampbell05** [comment]
Should be fixed in https://github.com/Supmenow/Sup-iOS/pull/1258
