### ISSUE TITLE
Add "Let's" Verb Before Flare Activity In French

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#122]
Add "Let's" Verb Before Flare Activity In French

Here is the sheet for the list of flares:

https://docs.google.com/spreadsheets/d/1YRV99PZWBOhVDHNUqPWm-3CcAzjd7D4fxcvHgG-7cUw/edit#gid=506566256

![image](https://cloud.githubusercontent.com/assets/1484989/16762186/53f6a89e-481b-11e6-89de-bc193fd89710.png)

**Comment by alexsup** [comment]
@jcampbell05 This is an in app change isn't it?

**Comment by jcampbell05** [comment]
@alexsup  Nope this is a resource file change, we just need the spreadsheet linked above to be updated by @roger-tan  or @juliensup or someone else who Parler en Français

**Comment by jcampbell05** [comment]
Fixed in https://github.com/Supmenow/Sup-iOS/pull/1249/files
