### ISSUE TITLE
User profile not centered precisley

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#137]
![image](https://cloud.githubusercontent.com/assets/1484989/16869127/287f8834-4a73-11e6-953a-5948b7bc8706.png)

**Comment by roger-tan** [comment]
<img width="1792" alt="screenshot 2016-07-15 14 42 18" src="https://cloud.githubusercontent.com/assets/3829527/16876065/62fec7e6-4a9a-11e6-8962-12426708ef69.png">

It's centered!
