### ISSUE TITLE
Friends aren't importing correctly from Digits.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#141]
We are uncertain we are importing digit friends correctly 

Locally, we need to:

1.  Confirm we import each friend correctly. We can do this with one HTTP request by sending a complete friend object payload.
2. Confirming success or failure of the HTTP Post.
3. Verbose logging that the above has been successful / unsuccessful
4. If unsuccessful, try 3 times in total. If after three times, log unsuccessful with as much info as possible.
5. On success, update firebase node /completedFriends with the {userID: true} via a push (so a uuid is created);

**Comment by jcampbell05** [comment]
Potentially related to https://github.com/Supmenow/sup-ios-issues/issues/140

**Comment by jcampbell05** [comment]
Tested now, this is fixed by #140 we can carry on any future fixes in that chain.
