### ISSUE TITLE
When creating users the identifier is a UUID rather than a facebook ID

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#142]
Our Firebase IDs have regressed.

They used to be facebook_{facebook_id} now they are UUID.

Why is this happening.

Fix.

**Comment by roger-tan** [comment]
Firebase change the response for the authentification provider data and expecialy the uid which is not facebook:{facebook identifier} but XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX
