### ISSUE TITLE
Joao couldn't select users in hangout

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#145]
When Joao was on create a sup
And he was trying to select phone contacts
Then he couldn't.

His mix panel is here:

https://mixpanel.com/report/835539/explore/#user?
distinct_id=7A4EEFC0-604F-45B0-B5DC-C845A4E54FDC

**Comment by jcampbell05** [comment]
@alexsup Tried to re-create this on `dev` and I regret to say I can't recreate it at the moment. I'll look at Mixpanel and Firebase to see if I can dig-out any interesting tid bits.

**Comment by jcampbell05** [comment]
Investigated Mixpanel and investigated the code nothing jumps out at me right now. 

@roger-tan  any ideas ? was he able to select them in the end ?

**Comment by roger-tan** [comment]
Email sent to Joao. Waiting to get a response from him.

**Comment by alexsup** [comment]
Great! Thanks dude.

**Comment by roger-tan** [comment]
<img width="1792" alt="screenshot 2016-07-15 14 42 18" src="https://cloud.githubusercontent.com/assets/3829527/16951231/0d3d401a-4dbc-11e6-9ffb-d7bd7128a900.png">

**Comment by roger-tan** [comment]
<img width="763" alt="screenshot 2016-07-19 14 21 04" src="https://cloud.githubusercontent.com/assets/3829527/16951257/20c277ae-4dbc-11e6-9b9e-2abfcd166a79.png">

**Comment by jcampbell05** [comment]
@roger-tan so he wasn't able to send the flare in the end ?

**Comment by jcampbell05** [comment]
Fixed in #1281 - Selection would be lost for users with large amounts of contacts due to the fact we incrementally load them in and refresh the UI which causes the selection to be lost.

We tweaked it to refresh the UI in such a way that it keeps track of already loaded users.

**Comment by roger-tan** [comment]
Just sent an email to Joao if he has a lot of contacts or not
