### ISSUE TITLE
Update reciprocal friendships

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#147]
We need to fix recursive friends:

1. Update firebase node when completed importing friends
2. Node.js will listen and create recursive friends
3. Facebook callback webhook on server

**Comment by alexsup** [comment]
@jcampbell05 is certain iOS is doing this locally.

**Comment by jcampbell05** [comment]
@alexsup  iOS handles both sides of the friendship.

**Comment by alexsup** [comment]
@jcampbell05 is this fixed by #140?

**Comment by jcampbell05** [comment]
@alexsup  This technically always worked for us, #140 fixes the importing saturation which blocks the import.

**Comment by alexsup** [comment]
@jcampbell05 Closing as to be fixed by #140 .
