### ISSUE TITLE
Empty State language isn't aligned with design.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#156]
- [ ] Update copy for english - We will have to make sure these are same key in POEditor across iOS and Android.
- [x] Updated white buttons to be same as blue hangout button.
- [x] Remove icon for contacts and locations disabled states for Radar and Friends List
- [x] Remove title for contacts and locations disabled states for Radar
- [x] Remove title for contacts and locations disabled states for Radar
- [x] Update Radar Empty state to match radar design (User profile followed by text)

**NOTE: Ignore removing the blocked list button for now. **

![ios empty states](https://cloud.githubusercontent.com/assets/13382954/17018154/5b09ca34-4f2e-11e6-8042-cbe3db9bb146.png)

**Comment by jcampbell05** [comment]
Will have to make sure these are same key in POEditor.

**Comment by jcampbell05** [comment]
Before starting work on this we should break this up into tasks.

**Comment by roger-tan** [comment]
For 4.6 or 4.7?

**Comment by jcampbell05** [comment]
Whatever is marked as the milestone for this issue.

**Comment by roger-tan** [comment]
![ios empty states](https://cloud.githubusercontent.com/assets/3829527/17098408/16adb182-525a-11e6-9a12-c5a83cf556ff.png)

Updated to the last Empty states
