### ISSUE TITLE
As a new user, my localUserID is not set up

### ISSUE THREAD

**Issue by roger-tan** [Supmenow/sup-ios-issues#158]
As a new users, my localUserID is not set up. That's means location background is not set up

`ARLog : 📍newLocation="<+51.50998000,-0.13370000> +/- 5.00m (speed -1.00 mps / course -1.00) @ 7/21/16, 3:41:58 PM British Summer Time" - horizontalAccuracy="5.0" verticalAccuracy="-1.0" altitude="0.0"`
`ARLog : 😎 Fetching localUserID for location update`
`ARLog : 😓 Error finding localUserID for location update`

**Comment by jcampbell05** [comment]
We should check the code in https://github.com/Supmenow/Sup-iOS/blob/dev/Sup/AppDelegate.swift is triggered.

**Comment by alexsup** [comment]
@roger-tan Great spot!

Good testing.

**Comment by roger-tan** [comment]
Should be fixed here (https://github.com/Supmenow/Sup-iOS/pull/1282)

**Comment by jcampbell05** [comment]
Regarding the new strategies here https://github.com/Supmenow/Sup-iOS/pull/1282#discussion-diff-71723484R188

I think the PR fixes the real bug and the strategy introduces un-needed complexity. We can keep it in this release see if any-body needs the new strategy but perhaps remove it when we are confident that `NSUserDefaults` is enougth.

We should also aim to have the code for setting all the analytics and `localUserID` data in a common place as it's copy and pasted twice in App Analytics and once in Login. We should do this either this week or next sprint.

Hopefully should make sure we aren't increasing maintenence costs.

**Comment by jcampbell05** [comment]
Implemented as part of 4.6 which is now released.
