### ISSUE TITLE
Remove technical keys from POEditor

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#164]
For example `facebook_app_id`, seems Xcode picked it up as something to be translated.

**Comment by roger-tan** [comment]
I agree. We should not provide keys from POEditor.

**Comment by jcampbell05** [comment]
Removed facebook app id here https://github.com/Supmenow/Sup-iOS/pull/1285

Will check for more and close this if I cant find any

**Comment by jcampbell05** [comment]
Can't see any others, closing.
