### ISSUE TITLE
Switch out smooch for messenger

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#180]

**Comment by jcampbell05** [comment]
Preparing the settings screen for this.

<img width="609" alt="screen shot 2016-08-16 at 16 14 47" src="https://cloud.githubusercontent.com/assets/1484989/17704319/a2b64f58-63cc-11e6-97c4-88e136ff0a83.png">

**Comment by jcampbell05** [comment]
Preparing the new settings screen.

![simulator screen shot aug 16 2016 16 21 47](https://cloud.githubusercontent.com/assets/1484989/17704631/8ddb1554-63cd-11e6-94fd-5dcf3beabf0d.png)

**Comment by jcampbell05** [comment]
Here is an initial design of what this could look like.

![simulator screen shot aug 16 2016 16 25 01](https://cloud.githubusercontent.com/assets/1484989/17704784/feb83af4-63cd-11e6-9fce-a211e576a1c5.png)

**Comment by jcampbell05** [comment]
https://github.com/Supmenow/Sup-iOS/pull/1300

**Comment by jcampbell05** [comment]
In dev
