### ISSUE TITLE
I can't choose a photo when creating a Flare

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#21]
I can only take a photo

**Comment by jcampbell05** [comment]
Will implement as part of version 5

**Comment by alexsup** [comment]
@jcampbell05 Surely this isn't an issue...

**Comment by jcampbell05** [comment]
@alexsup  what do you mean ?

**Comment by alexsup** [comment]
@jcampbell05 This should be in Jira not here :)

Closing
