### ISSUE TITLE
Some already verified users are requested to verify their number for Digits.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#3]
It seems that there is a case where users are being prompted to verify their number even though they have already validated.

What we know:
- When a user validated upon upgrade their Digits ID wasn't being stored.

What we've fixed:
- The Digits ID is always stored no matter which path a user verified their number via.

Questions left to answer:
- Are some users actually cancelling and not realising ?
- Is there some sort of error we aren't handling from digits ? 
- Why for some users does this screen stop appearing when we attempt to debug ?

Potential issue:
- Is this process confusing users ?
- Is there an issue with Digits on poor networks or other situations ?

**Comment by jcampbell05** [comment]
We've added some additional logs for errors and success for Digits to gather more information. Pushing to Testflight for affected users to test.

**Comment by jcampbell05** [comment]
@alexsup  Tested `3.7.1 (Jaffa 2)` with the fix from @roger-tan .

I can confirm that the code detects that the user has a digits ID and no-longer prompts them.

**Comment by jcampbell05** [comment]
What we know so far: 
- New code is more defensive about not being able to get the user.
- Even if the user is not found and we try to login via digits. Digits will only show login UI if the user isn't logged in (So we may not even need that defensive code).
- The user can only be logged out by the session becoming invalid.
- The session becomes invalid if:
   - The user logs out from digits.com
   - The app logs them out.
   - Some other unspecified reason (Awaiting clarification of these reasons from the Digits Team and how exactly digits restores the session).
- The session doesn't have a time limit.
- It seems to happen more on slow network connections but so far has been unreproducible.
- Digits should cache the session between installs on the keychain.
- The user who last had this, had recently changed his phone number.
- The Digits ID is successfully updated in all situations.

We are now logging when a session becomes invalid so we know this is what caused the screen to show,  unfortunately if a session becomes invalid we still have to show the login screen but at least we know it may not be a bug.

We have also contacted Digits to find out if there are other situations this login UI could be shown, hopefully digits should actually be handling slow networks and it's just a bug on their side.

**Comment by alexsup** [comment]
@jcampbell05, @roger-tan 

Just a quick reminder: when logging for development rather than growth, please report to Logentries rather than Mixpanel :)

**Comment by jcampbell05** [comment]
Potentially fixed with our Digits tweak.

**Comment by alexsup** [comment]
@jcampbell05 Closing due to no further feedback.
