### ISSUE TITLE
iOS App Takes 30 minutes to build

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#49]
The Ideal time would be 2 minutes and a more acceptable time is 10 minutes.

Build Time Breakdown So Far (Time in seconds):

- Verifying required fastlane version | 0           |

- default_platform                    | 0           |

- xcake + CocoaPods                             | 284         |

- match                               | 9           |

-  match                               | 5           |

-  match                               | 4           |

- match                               | 6           |

-  match                               | 8           |

-  match                               | 6           |

-  match                               | 5           |

-  match                               | 4           |

-  match                               | 4           |

- scan                                | 1194        |

-  slack                               | 0           |

Overview:

- 10 minutes for tools to build up dependencies for the project.
- 20 minutes to build the App and it's CocoaPods.

Techniques:
- [ ] Remove unused libraries if any.
- [ ] Switch away from any libraries which are overkill or un-needed (Parse just for notifications, one library used just to let the use know if they shared).
- [ ] Pre-compile Cocoapods using https://github.com/neonichu/Rome/ (Requires us to update to 1.0)
- [ ] Use https://github.com/jcampbell05/cocoapods-deploy/ to pull down the version we need and remove need to update Cocoapod's spec repo.
- [ ] Look at any swift code that is slowing down the compiler (i.e CoreMotions's animations) - https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode or https://engineering.tumblr.com/post/144151794436/swift-compilation-reporting-at-tumblr?utm_campaign=This%2BWeek%2Bin%2BSwift&utm_medium=email&utm_source=This_Week_in_Swift_87
- [ ] Break app into libraries.
- [x] Only pull down certificates we need (match)
- [ ] Work with match to implement certificate matrix which reduces number of times match has to clone and decrypt.

**Comment by jcampbell05** [comment]
@alexsup Shaved around 30 seconds to a minute with https://github.com/Supmenow/Sup-iOS/issues/952

**Comment by alexsup** [comment]
@jcampbell05 is this still an issue?

**Comment by jcampbell05** [comment]
@alexsup  Yes, won't be one that we can solve in one go, it is a lot faster since we remove chat.

**Comment by alexsup** [comment]
@jcampbell05 Ok, let's move to Jira.

Closing
