### ISSUE TITLE
Some users aren't identified with Smooch.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#50]
It seems there are certain situations where users aren't identified with smooch.

However we do get their Firebase ID etc, just not their name:

<img width="871" alt="screen shot 2016-05-17 at 10 56 26" src="https://cloud.githubusercontent.com/assets/1484989/15318467/0729fb84-1c1e-11e6-85d1-e718d9a342ac.png">

**Comment by alexsup** [comment]
@jcampbell05 Is this the same problem with Logentries and Radar and potentially Firebase?

**Comment by jcampbell05** [comment]
@alexsup Maybe.

**Comment by alexsup** [comment]
@jcampbell05 Any update?

**Comment by jcampbell05** [comment]
@alexsup  I haven't seen it in a while so maybe it was a one off during testing ?

**Comment by alexsup** [comment]
@jcampbell05 I'm archiving this. We can reopen if we see it again
