### ISSUE TITLE
Flares are global

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#51]
Given I create a flare
When Rich is on the other side of the world
Then he gets my flare in the activity list

**Comment by alexsup** [comment]
@jcampbell05 For clarification, they don't get notifications.

**Comment by jcampbell05** [comment]
@alexsup I'm thinking this will be handled when we have a object system and a special node for activity.

**Comment by alexsup** [comment]
@jcampbell05 Yes.

**Comment by jcampbell05** [comment]
No longer global as of 4.4
