### ISSUE TITLE
When Log Entries is ran in the background it doesn't know the LocalUserID

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#52]
<img width="868" alt="screen shot 2016-05-17 at 11 09 33" src="https://cloud.githubusercontent.com/assets/1484989/15318825/dc175afc-1c1f-11e6-9f71-2106d979d069.png">

Notice how above during a background location update, Log Entries is unable to know who the UserID is.

**Comment by alexsup** [comment]
@jcampbell05 Good spot!

**Comment by alexsup** [comment]
@jcampbell05 Can you explore?

**Comment by jcampbell05** [comment]
@alexsup sure, which sprint this one ?

**Comment by alexsup** [comment]
@jcampbell05 I'm getting the impression that this is a core problem. If there is time in 4.5, I'd like a spike.

Otherwise 4.6 please

**Comment by jcampbell05** [comment]
I wasn't able to recreate this in 4.3 so far but I'll keep an eye out.

**Comment by alexsup** [comment]
@jcampbell05 Shall we keep this open?

**Comment by jcampbell05** [comment]
@alexsup  yes for now, we can close it in a couple of weeks once 4.2 and 4.3 are in the app store to see if we still get it.

**Comment by alexsup** [comment]
👍 Closing.
