### ISSUE TITLE
Improve Application Performance On 3G

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#55]

**Comment by alexsup** [comment]
@jcampbell05 This isn't an issue.

Please can you clarify?

**Comment by jcampbell05** [comment]
@alexsup true, right now the app can be slow on 3G networks which other apps can cope.

I believe ours should be able to handle it.

**Comment by alexsup** [comment]
@jcampbell05 can we profile it?

Do we have specific data on what is causing problems?

**Comment by jcampbell05** [comment]
@alexsup  We can profile it in specific areas in the app i.e The Radar.
We had some idea in our Epic in JIRA.

**Comment by alexsup** [comment]
@jcampbell05 Would moving to a friends API help?

**Comment by jcampbell05** [comment]
Not sure would have to profile it but maybe not

**Comment by alexsup** [comment]
@jcampbell05 Moving to Jira
