### ISSUE TITLE
Letters are too big for circle in create a flare view

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#67]
![unnamed 3](https://cloud.githubusercontent.com/assets/13382954/15578818/e6090830-2359-11e6-8073-81a962a7f473.png)

**Comment by jcampbell05** [comment]
Will move the view for this to a common component :)

**Comment by roger-tan** [comment]
Should be fixed in PR [#1024](https://github.com/Supmenow/Sup-iOS/pull/1024)

**Comment by alexsup** [comment]
👍 
Closing
