### ISSUE TITLE
No empty screen when contact permissions are refused.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#76]

**Comment by jcampbell05** [comment]
@alexsup  which screen is this ?

**Comment by alexmbarton** [comment]
@jcampbell05 Apologies.

Given I have not allowed contacts permissions
When I am on the radar
And I tap hang out
Then I do not see contacts
And I am not informed that I have not allowed contacts

**Comment by jcampbell05** [comment]
Should be fixed in 4.3
