### ISSUE TITLE
Activity / location / photo lose state when returning to invitees

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#78]
Given I have chosen friends to send the flare to 
And I have chosen an activity, location and photo
When I return to change the users selected
And I return to the flare screen
Then It forgets the activity, location and photo

**Comment by alexsup** [comment]
@roger-tan Does this have state yet?

**Comment by roger-tan** [comment]
Not yet

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan Any movement on this?

Closing as not an issue. More a feature.
