### ISSUE TITLE
Remove friends on sup in invite friends

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#82]
Given I'm on the radar
When I click on Invite friends
Then I should not see friends I've already invited

It doesn't belong there.

**Comment by alexsup** [comment]
@roger-tan 👍

**Comment by roger-tan** [comment]
I think, it's already implemented from PR [#1047](https://github.com/Supmenow/Sup-iOS/pull/1047) but needs optimization to load much faster.
