### ISSUE TITLE
Prompt for get directions when I click on the map.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#83]
Given I'm on a flare preview
When I click on the map
Then I should get a pop up for directions

Same behaviour as clicking on directions

**Comment by jcampbell05** [comment]
@alexsup I'm not sure if this makes sense:

- Some uses expect a double-tap to zoom.
- Some users expect a tap on the map to expand.

**Comment by alexsup** [comment]
@jcampbell05 This should happen as per flinto.

Ask Pierre for details.

**Comment by jcampbell05** [comment]
Okay the Flinto is different than what this issue describes, so I'll close this.
