### ISSUE TITLE
Sent to avatars are too close together on flare preview

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#84]
![unnamed 12](https://cloud.githubusercontent.com/assets/13382954/15888997/36037ca6-2d61-11e6-8dc0-55c2c0593a44.png)

**Comment by alexsup** [comment]
@roger-tan Has this been fixed?

**Comment by roger-tan** [comment]
No.

**Comment by roger-tan** [comment]
Should be fixed here (https://github.com/Supmenow/Sup-iOS/pull/1212)
