### ISSUE TITLE
Radar taking a long time to download avatars

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#86]
The following image was taken 30 seconds after the app was opened.

![unnamed 14](https://cloud.githubusercontent.com/assets/13382954/15889119/b72e3f64-2d61-11e6-8443-b5b0232952be.png)

**Comment by jcampbell05** [comment]
This isn't due to the image download speeds the library for the radar view currently renders a snapshot, I've forked it an tweaked it to use the live view.
