### ISSUE TITLE
Odd behaviour from an investor

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#87]
I've enclosed a screenshot - basically the bottom nav just changed & I've just closed & opened the app twice and wasn't getting any click through, neither from the bottom nav nor from the top nav. Having said this, it's working again now. I'm wondering whether it's worth adding in a short message when this happens saying 'oops, please close & re-open the app' or something similar, ensuring users don't just close the app & don't return / and to avoid any negative WOM etc.

![image](https://cloud.githubusercontent.com/assets/13382954/15889267/6728c4fc-2d62-11e6-8670-7e0b43aaef29.png)

**Comment by jcampbell05** [comment]
@alexsup  so the app was frozen ?

**Comment by alexsup** [comment]
@jcampbell05 Closing due to lack of informaiton
