### ISSUE TITLE
Make distance of User on Radar depend on Location Node distance not user profile distance.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#88]
Currently if user profile is cached with old location they can be further out than the radar data tells us they are, hence discrepancy between the profile and radar.

We could wrap them in an object like so:

`RadarObject(item: User, distance: 200)`

Especially when we move to the new Radar API the distance of a user should be based on the distance from their location node. When we add flares we will have to do the same as our Radar will be object based.

I'm not sure how this effects distance for the friends list, we maybe will have to tweak the design there.

**Comment by alexsup** [comment]
@jcampbell05 This is not an issue. Closing
