### ISSUE TITLE
Improve feedback whilst we are updating radar.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#89]
When we have a new location but are updating users we should have some feedback that the current users are out of date and we are currently updating.

i.e a pulsating centre user ?

**Comment by alexsup** [comment]
@roger-tan Can you let me know your ideas for this?

**Comment by jcampbell05** [comment]
@alexsup  There is a new design for this, next sprint we should implement the avatar in the middle of the radar. I think there is a pulse effect when updating.

**Comment by jcampbell05** [comment]
Fixed so we show loading state whilst updating, will talk to Rhys about getting a better design.
