### ISSUE TITLE
Contacts empty screen prompt buttons the wrong way round

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#92]
Given I have no contacts
When I click allow contacts
Then I get a how-to alert
And the buttons are the wrong way round

![unnamed 16](https://cloud.githubusercontent.com/assets/13382954/16190898/7503ec48-36d9-11e6-900b-82c2e71a2c7c.png)

**Comment by jcampbell05** [comment]
Should be fixed in 4.4
