### ISSUE TITLE
[EXTERNAL] Digits country code error

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#94]
Hi there
I've encountered a bug that's stopping me signing in, so you'll probably want to fix this asap...

After signing in with Facebook on my iPhone, I get the 'What's your phone number?' page, which is set to Australia +61. I can't change this to UK, and it doesn't recognise my UK number in this format, so I can't get the confirmation code. :(

Look forward to your reply,
Caroline

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan I've asked Caroline to provide us with a screenshot of the digits screen.

We're also to keep her updated 💯

**Comment by alexsup** [comment]
![unnamed 17](https://cloud.githubusercontent.com/assets/13382954/16223350/bf7c0182-3794-11e6-8f9d-6f24f5ab289a.png)

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan 

The reply:

Ah! Yes, I had no idea I needed to do that - but all working now.

Can I suggest you don't have it set to Australia as default? I'm an app founder myself and tapping to change the code didn't even cross my mind (unless it's just me being stupid, of course!)

Anyway, I look forward to exploring the app and wish you the best of luck with it!
Caroline

**Comment by jcampbell05** [comment]
Yeah I always thought the way digits switched country codes wasn't obvious.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan closing
