### ISSUE TITLE
Nearby Notification triggered sparadically.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-ios-issues#98]
From a user
"(Sup) Only alerting you when other SUP users are nearby sporadically. i.e. Taylor and I met up 3 different times at 3 different places and neither of us got a SUP notification that the other was nearby until we were in the Uber home after the 3rd meet up."

**Comment by jcampbell05** [comment]
User was on an older version of the App but will verify this works on latest version of the app.

**Comment by alexsup** [comment]
@jcampbell05 Great. Thanks dude.

**Comment by alexsup** [comment]
@jcampbell05 new API will fix this.

**Comment by jcampbell05** [comment]
@alexsup We should intergration test this then I will close as I think the user was on an older version.

**Comment by alexsup** [comment]
@jcampbell05 we can only do this manually.

It all tests my end.

**Comment by jcampbell05** [comment]
I would like to do this manually :) are you able to trigger your profile entering Runway east and getting a notification by removing and adding your location ?

**Comment by jcampbell05** [comment]
@alexsup Will monitor the nearby notifications with your new API stack, we should start mesuring metrics for this to see if this has improved.

**Comment by alexsup** [comment]
I feel this is fixed now
